name: TeaTimer
options:
  bundleIdPrefix: com.raymondluo
  deploymentTarget:
    iOS: "16.2"
  developmentLanguage: en
  createIntermediateGroups: true
  automaticCodeSigning:
    style: automatic
    teamID: "3FCB3DCBK9"

targets:
  TeaTimer:
    type: application
    platform: iOS
    deploymentTarget: "16.2"
    sources:
      - path: TeaTimer
        name: TeaTimer
        createIntermediateGroups: true
    settings:
      base:
        INFOPLIST_FILE: TeaTimer/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.raymondluo.teatimer
        PRODUCT_NAME: "Gongfu Tea Timer"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "3FCB3DCBK9"
    scheme:
      testTargets:
        - TeaTimerTests
        - TeaTimerUITests

  TeaTimerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TeaTimerTests
    dependencies:
      - target: TeaTimer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raymondluo.teatimer.tests
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES

  TeaTimerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - TeaTimerUITests
    dependencies:
      - target: TeaTimer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raymondluo.teatimer.uitests
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES

schemes:
  TeaTimer:
    build:
      targets:
        TeaTimer: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TeaTimerTests
        - TeaTimerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
